### ISSUE TITLE
time and date for the course

### ISSUE THREAD

**Issue by rasi** [fredhutchio/tfcb#1]
I need to give time and days for our course to Maia Low so that our Conjoint course can be listed in the time schedule.

1. Does offering a conjoint course in the first half of Fall quarter (end of September to beginning of November, 5 weeks) work for everyone? If not we could do the second half of Fall. We will each be teaching 1-2 weeks so we can always adjust between ourselves if specific dates do not work.

2. Day and times: How about Tues/Thurs 330 to 440? If that does not work, suggest alternate times.

**Comment by rasi** [comment]
I am also taking for granted that we will have it at the Hutch.

**Comment by jbloom** [comment]
I'm fine with Tuesday and Thursday from 3:30 to 4:40. I can do either the first or second half of the fall quarter. Not sure which is better.

I definitely concur we should have it at the Hutch.

The only thing that we should check is that 3:30 to 4:40 doesn't interfere with some other important MCB course that many students take. If it's not obvious from looking at the course schedule, we could ask MCB students (maybe Sidney Bell and Caelan Radford?).

**Comment by phbradley** [comment]
Sounds good. I have a commitment this semester on Tuesday afternoons but I'm not even sure that it will be at the same time next year. Worst case I could do Thursday but not Tuesday, so no worries.

**Comment by rasi** [comment]
Just as an update, I am awaiting the time schedule from Maia Low so that we can avoid any slot clashes as Jesse recommended.
This is the email from Maia for record:
```
Laura Masserman is working on the Autumn schedule for MCB courses right now.  
As soon as that is confirmed, the three of us can figure out the best time for your course. 
I have already requested to add it to the Time Schedule (with a time and place TBD)
and I’ll let you know when I get confirmation about that, too.
```

**Comment by rasi** [comment]
@jbloom @phbradley @trvrb How does having the TFCB class between 9/27/18 – 10/30/18, Tu-Thu 3:20-4:40 work for all of you? 

As we discussed, we could do a 3 + 2 + 3 + 2 split of the 10 total classes between the 4 of us. Depending on your schedules, we could find a single contiguous chunk for each of us.

The class will be in one of the B-suites  B1-072/074/076.

There are 23 incoming MCB students. We could put a class cap of 20 and give priority to first-year MCB students. Let me know if you think a different arrangement will work better.

**Comment by phbradley** [comment]
That works fine for me @rasi 
-Phil

**Comment by jbloom** [comment]
@rasi: This works fine for me. I am gone Oct 10-12, so should not take that block.

Can you confirm as soon as you finalize time and I will put it on my calendar then.

As soon as we find time, we should figure out how to get word out for class to new students!

**Comment by trvrb** [comment]
@rasi: Dates work for me as well, as does the course split and capping the course to 20 students.

**Comment by rasi** [comment]
The schedule for the TFCB course is confirmed as 9/27/18 – 10/30/18, Tu-Thu 3:20-4:40.  Please put it on your calendar.
