### ISSUE TITLE
information for course flyer

### ISSUE THREAD

**Issue by rasi** [fredhutchio/tfcb#2]
I am providing the following information for creating the course flyer. Please edit with any of your suggestions. I will send this out to the MCB staff on Thursday afternoon at 4.

**Course Faculty**

The course will be taught jointly by four faculty in the Computational Biology Program at Fred Hutch:
- Trevor Bedford  
- Jesse Bloom  
- Phil Bradley  
- Arvind Rasi Subramaniam

**Course Description**

This course will introduce students to established best practices in computational biology. Students will learn to organize unstructured data into standard formats, transform data for statistical analyses, and visualize the transformed data. Students will learn workflows for reproducible research such as version control, project organization, and code documentation. Students will gain basic experience with Unix command line tools and the Python and R programming languages. Classes will involve hands-on learning through coding exercises, collaborative problem solving, and extensive use of online learning resources.

**Other Information**

Grading: Class participation (25%), Homework assignments (50%), Final assignment (25%)

Basic experience with programming in any language will be helpful but is not required.

Enrollment is limited to 20 students. Priority will be given for first year MCB students. No auditors are allowed.

**Comment by trvrb** [comment]
Thanks is excellent @rasi. I can't think of anything to change.

**Comment by phbradley** [comment]
Agreed! Looks great.

**Comment by jbloom** [comment]
I also think this looks great. Only possible very minor suggestion is to replace _Unix_ with _Linux_. I'm not sure if people even use or know what _Unix_ is any more?

**Comment by jbloom** [comment]
Sorry, one last suggestion. Do we want to create a stub course webpage and then include that in this initial announcement too? Or we can wait, just a thought.
