### ISSUE TITLE
website for tfcb

### ISSUE THREAD

**Issue by rasi** [fredhutchio/tfcb#3]
@matsen Jesse had the the good idea of creating a rudimentary website for the TFCB course to include in the course flyer (#2). Not sure how easy to set up, but do you think we can host it as tfcb.fredhutch.io? This will keep the course under the umbrella of fredhutch.io.

**Comment by trvrb** [comment]
I think the easiest way to do this (and have everyone easily able to push to a website) is through GitHub pages. I don't know how familiar you are, but basically GitHub will run Jekyll for you and create a static website. If we enabled GH Pages for this repo, we'd end up with the URL `fredhutchio.github.io/tfcb`. If @matsen has access to DNS records for `fredhutch.io` domain then it's easy to point an ALIAS from `tfcb.fredhutch.io` to `fredhutchio.github.io/tfcb`.

https://help.github.com/articles/quick-start-setting-up-a-custom-domain/

**Comment by rasi** [comment]
Good idea. I will create a new branch for Github pages and provide `fredhutchio.github.io/tfcb` as the website address for now.

**Comment by rasi** [comment]
The course website is now running at https://fredhutchio.github.io/tfcb/. Please feel free to make any changes. The markdown files are located in the gh-pages branch of this repo. @matsen If you can alias tfcb.fredhutch.io to above, that will be perfect.
