### ISSUE TITLE
assigning lecture dates and syllabus

### ISSUE THREAD

**Issue by jbloom** [fredhutchio/tfcb#5]
@rasi @phbradley @trvrb: I was thinking that perhaps we should assign the specific dates each of us will teach relatively soon, so that we can mark that on our calendars before they fill up.

Any thoughts on the schedule for teaching?

**Comment by rasi** [comment]
Let me come up with a rough syllabus this weekend. Once we agree on the syllabus, we can decide on specific dates for each of us. I am guessing the syllabus + what each of us wants to teach will constrain the dates somewhat.

**Comment by rasi** [comment]
All of us should attend the first class if you are around: Sep 26, 3:20 - 4:40 PM, B1-072

**Comment by rasi** [comment]
@jbloom @trvrb @phbradley I have created a draft syllabus that is a bit modified and re-organized from our earlier one. 
https://github.com/fredhutchio/tfcb/blob/master/syllabus.md

I have also indicated the tentative instructors in the heading.
Please assign yourself to any of the classes. 

The syllabus is very rough and I have put down some ideas as they came up. So feel free to modify the topics or class order as you deem fit.

Let us aim to have the class dates for each of us nailed down by this friday (6/15).

**Comment by jbloom** [comment]
@rasi: Thanks.

If it works for others, I'd be most interested in focusing on classes 7-9. I actually wonder if we should flip the current classes 8 and 9, so that we focus on Python data structures first and then BioPython and protein structures. If that works. I could teach 7 and 8, and then co-teach 9 with @phbradley. 

For class 1, I think @trvrb might be better at this than me?

For class 5, I'm actually not that great at the command line, so I'm wondering if @phbradley might be better at teaching this than me?

If these changes sound good to others, let me know and I can update syllabus.

**Comment by phbradley** [comment]
This looks good. I am happy with most of the places where my name appears, with the following comments:

- class 5: I can do this but I would almost prefer to teach it after at least one python class because I really like doing "command line" things from python, ie using python to automate file-system and other tasks. That's how I do more complex cluster submission, for example. So I would propose to move it later and add in some python-related content.

- class 7: looks good

- class 8: I might not be the best here, since I haven't used biopython/jupyter all that much (I'm looking forward to learning from this class!). Mostly stick to scipy/scikit-learn/numpy...

- class 9: looks good

- class 10: Embarrassed to admit that I haven't used any of those tools! Definitely could do the git stuff. Also think the student-led idea would be fine.

Thanks for leading the charge, @rasi!




----- Original Message -----

**Comment by rasi** [comment]
@phbradley I think students will benefit from introduction to numpy/scipy/scikit-learn. For eg. how to handle matrices, fit a linear curve etc. Do you think you could do this as class 9 using some research problem as an example? In that case, we could combine the current classes 7+8+9 into 2 lectures 7+8,  perhaps dropping some topics such as protein structure parsing, debugging, creating custom package.

**Comment by jbloom** [comment]
Based on @phbradley's comments two above, we could also just consider jettisoning the "command line" part of class 5, and just making it more Python with a bit emphasizing command-line like operations.

I also do most of my "command line" things from Python, which is why I don't  feel qualified to teach the current class 5.

**Comment by rasi** [comment]
The `advanced command line` title was a misnomer on my part. I am thinking of topics like installing software from source using `make`, customizing command line using `bashrc` and `bash_profile` -- so stuff you do at the command line, but not really about the command line.

@jbloom: after the comp bio lunch, @trvrb @phbradley and I had a brief meeting where we reorganized some of the classes and discussed who would teach what.

The updated syllabus is here: https://github.com/fredhutchio/tfcb/blob/master/syllabus.md

Our current thinking is it might work well if the initial half of the course gets done with `R` and the second half is `python` focused.

@trvrb and @phbradley both volunteered for some of the `python` classes. We now have a mix of all 3 of you teaching in the second half of the course.

We have replaced the last class with some introduction to `scipy`, `numpy`, `scikit-learn`. We thought it will be useful if people learn a bit of clustering and linear modeling analysis.

@trvrb was wondering if you could teach the introduction class? He will be coming back into town only the day before, so it would work well if you could teach that. 

I am hoping to make it to all the classes, so I am happy to pitch in for any of the classes.

**Comment by jbloom** [comment]
This all works for me.

**Comment by rasi** [comment]
Ok, we will go with these lecture assignments then. Don't forget to put the dates on your calendar!

**Comment by trvrb** [comment]
@jbloom ---

I now have a commitment I really don't want to miss on Sep 27 (WHO flu VCM meeting). Jesse, could you take class 1 on Sep 27? This would give:

Jesse: 2 classes
Rasi: 3 classes
Trevor: 2 classes
Phil: 3 classes

Would this be alright?

**Comment by rasi** [comment]
@trvrb Sorry, forgot to update here, but @jbloom already agreed to do the Sept 27 class. See the new repo README for dates.

**Comment by trvrb** [comment]
Great. Thanks Jesse and Rasi.
